from sqlalchemy.orm import Session
import models

INITIAL_ITEMS = [
  { "id": 1, "name": "DISPLAY", "location": "BO-EST-01", "stock": 23, "in_use": 0, "damaged": 0, "avail": 23, "cost_center": "Informática", "category": "Displays y Pantallas" },
  { "id": 2, "name": "LCD 16X2", "location": "BO-DE-B", "stock": 29, "in_use": 1, "damaged": 0, "avail": 28, "cost_center": "Informática", "category": "Displays y Pantallas" },
  { "id": 3, "name": "CAJA DE RESISTENCIAS", "location": "BO-EST-01", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Ambas Carreras", "category": "Componentes Pasivos" },
  { "id": 4, "name": "RELAY / RELE", "location": "BO-DE-01", "stock": 20, "in_use": 0, "damaged": 0, "avail": 20, "cost_center": "Informática", "category": "Actuadores y Módulos" },
  { "id": 5, "name": "BUZZER / ZUMBADOR", "location": "BO-EST-01", "stock": 20, "in_use": 0, "damaged": 0, "avail": 20, "cost_center": "Industrial", "category": "Audio y Sonido" },
  { "id": 6, "name": "RELOJ RTC", "location": "BO-DE-C-04", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Módulos Electrónicos" },
  { "id": 7, "name": "SENSOR MICRÓFONO", "location": "BO-DE-C-01", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Sensores" },
  { "id": 8, "name": "Caja de luces LED", "location": "BO-EST-01", "stock": 9, "in_use": 0, "damaged": 0, "avail": 9, "cost_center": "Ambas Carreras", "category": "Optoelectrónica" },
  { "id": 9, "name": "Sensor Calidad del Aire", "location": "BO-DE-C-01", "stock": 10, "in_use": 0, "damaged": 0, "avail": 10, "cost_center": "Industrial", "category": "Sensores" },
  { "id": 10, "name": "Fin de Carrera (Limit Switch)", "location": "BO-DE-C-01", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Sensores" },
  { "id": 11, "name": "NODEMCU ESP8266", "location": "BO-DE-D", "stock": 40, "in_use": 7, "damaged": 5, "avail": 28, "cost_center": "Informática", "category": "Microcontroladores e IoT" },
  { "id": 12, "name": "Ventilador 10x10 12v", "location": "BO-EST-01", "stock": 5, "in_use": 0, "damaged": 0, "avail": 5, "cost_center": "Industrial", "category": "Refrigeración y Mecánica" },
  { "id": 13, "name": "BATERÍA 9v", "location": "BO-IZ-E,F", "stock": 24, "in_use": 3, "damaged": 0, "avail": 21, "cost_center": "Industrial", "category": "Alimentación y Baterías" },
  { "id": 14, "name": "Sensor pulso cardíaco MAX30102", "location": "BO-DE-C-01", "stock": 5, "in_use": 0, "damaged": 0, "avail": 5, "cost_center": "Informática", "category": "Sensores Biomédicos" },
  { "id": 15, "name": "FUENTE 5v 2A", "location": "BO-DE-B", "stock": 10, "in_use": 0, "damaged": 0, "avail": 10, "cost_center": "Industrial", "category": "Alimentación y Fuentes" },
  { "id": 16, "name": "FUENTE 12v", "location": "BO-DE-B", "stock": 24, "in_use": 0, "damaged": 0, "avail": 24, "cost_center": "Informática", "category": "Alimentación y Fuentes" },
  { "id": 17, "name": "PILA D2", "location": "BO-IZ-E,F", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Industrial", "category": "Alimentación y Baterías" },
  { "id": 18, "name": "PILA AA+", "location": "BO-IZ-E,F", "stock": 30, "in_use": 3, "damaged": 0, "avail": 27, "cost_center": "Industrial", "category": "Alimentación y Baterías" },
  { "id": 19, "name": "PILA AAA+", "location": "BO-IZ-E,F", "stock": 18, "in_use": 0, "damaged": 0, "avail": 18, "cost_center": "Industrial", "category": "Alimentación y Baterías" },
  { "id": 20, "name": "PILA C2", "location": "BO-IZ-E,F", "stock": 10, "in_use": 0, "damaged": 0, "avail": 10, "cost_center": "Informática", "category": "Alimentación y Baterías" },
  { "id": 21, "name": "Lente de seguridad transparente", "location": "BO-IZ-E,F", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Seguridad y EPP" },
  { "id": 22, "name": "PORTA LÁMPARA", "location": "BO-DE-B", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Informática", "category": "Electricidad" },
  { "id": 23, "name": "AMPOLLETA", "location": "BO-DE-B", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Electricidad" },
  { "id": 24, "name": "Kit Taladro Bauker 600 W", "location": "BO-IZ-E,F", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Herramientas Eléctricas" },
  { "id": 25, "name": "BANANA PI", "location": "BO-DE-C-04", "stock": 8, "in_use": 0, "damaged": 0, "avail": 8, "cost_center": "Informática", "category": "SBC y Procesadores" },
  { "id": 26, "name": "CASE BANANA PI", "location": "BO-DE-C-04", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Informática", "category": "Accesorios y Carcasas" },
  { "id": 27, "name": "Puntero Láser", "location": "BO-DE-B", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Optoelectrónica" },
  { "id": 28, "name": "Case Arduino", "location": "BO-DE-B", "stock": 10, "in_use": 0, "damaged": 0, "avail": 10, "cost_center": "Informática", "category": "Accesorios y Carcasas" },
  { "id": 29, "name": "Shield V5.0 Arduino", "location": "BO-DE-B", "stock": 6, "in_use": 0, "damaged": 0, "avail": 6, "cost_center": "Industrial", "category": "Shields y Expansión" },
  { "id": 30, "name": "KIT RaspBerry PI 4", "location": "BO-DE-C-04", "stock": 6, "in_use": 4, "damaged": 0, "avail": 2, "cost_center": "Informática", "category": "SBC y Procesadores" },
  { "id": 31, "name": "Arduino Uno", "location": "BO-DE-D", "stock": 55, "in_use": 9, "damaged": 2, "avail": 44, "cost_center": "Informática", "category": "Microcontroladores e IoT" },
  { "id": 32, "name": "Arduino Mega", "location": "BO-DE-D", "stock": 1, "in_use": 1, "damaged": 0, "avail": 0, "cost_center": "Industrial", "category": "Microcontroladores e IoT" },
  { "id": 33, "name": "Zapatilla Eléctrica", "location": "BO-DE-B", "stock": 8, "in_use": 1, "damaged": 1, "avail": 6, "cost_center": "Informática", "category": "Electricidad" },
  { "id": 34, "name": "Alargador Eléctrico", "location": "BO-DE-B", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Electricidad" },
  { "id": 35, "name": "Pistola Silicona", "location": "BO-IZ-E,F", "stock": 8, "in_use": 0, "damaged": 2, "avail": 6, "cost_center": "Industrial", "category": "Herramientas Manuales" },
  { "id": 36, "name": "Conector batería (Porta Baterías)", "location": "BO-IZ-E,F", "stock": 79, "in_use": 9, "damaged": 0, "avail": 70, "cost_center": "Informática", "category": "Alimentación y Baterías" },
  { "id": 37, "name": "Pie de Metro (Calibre)", "location": "BO-IZ-E,F", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "Instrumentos de Medición" },
  { "id": 38, "name": "Cinta métrica 7,5 m", "location": "BO-IZ-E,F", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Industrial", "category": "Instrumentos de Medición" },
  { "id": 39, "name": "Escuadra de Medición", "location": "BO-IZ-E,F", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Instrumentos de Medición" },
  { "id": 40, "name": "Serrucho de Costilla", "location": "BO-IZ-E,F", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Herramientas Manuales" },
  { "id": 41, "name": "Sierra Manual", "location": "BO-IZ-E,F", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Herramientas Manuales" },
  { "id": 42, "name": "Espátulas", "location": "BO-IZ-E,F", "stock": 5, "in_use": 0, "damaged": 0, "avail": 5, "cost_center": "Industrial", "category": "Herramientas Manuales" },
  { "id": 43, "name": "Hojas de Sierra Repuesto", "location": "BO-IZ-E,F", "stock": 5, "in_use": 0, "damaged": 0, "avail": 5, "cost_center": "Industrial", "category": "Consumibles" },
  { "id": 44, "name": "Brocha 3 pulgadas", "location": "BO-IZ-E,F", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Herramientas Manuales" },
  { "id": 45, "name": "Kit de Herramientas de Computador", "location": "BO-IZ-E,F", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Industrial", "category": "Herramientas Manuales" },
  { "id": 46, "name": "Pliego de lija p320", "location": "BO-IZ-E,F", "stock": 4, "in_use": 1, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "Consumibles" },
  { "id": 47, "name": "Soplador Eléctrico", "location": "BO-IZ-E,F", "stock": 2, "in_use": 1, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Herramientas Eléctricas" },
  { "id": 48, "name": "Osciloscopio portátil", "location": "BO-IZ-E,F", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Instrumentos de Medición" },
  { "id": 49, "name": "Cable micro USB", "location": "BO-IZ-E,F", "stock": 16, "in_use": 0, "damaged": 0, "avail": 16, "cost_center": "Informática", "category": "Cables y Conectores" },
  { "id": 50, "name": "Wireless 3 Axis magnetic field sensor", "location": "OF-REP-D,E", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Sensores" },
  { "id": 51, "name": "PROTOBOARD", "location": "BO-IZ-D", "stock": 39, "in_use": 4, "damaged": 0, "avail": 35, "cost_center": "Ambas Carreras", "category": "Prototipado" },
  { "id": 52, "name": "Lector + microSD", "location": "BO-IZ-D", "stock": 9, "in_use": 5, "damaged": 0, "avail": 4, "cost_center": "Informática", "category": "Memorias y Almacenamiento" },
  { "id": 53, "name": "Radar Módulo", "location": "OF-REP-A,B", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Sensores" },
  { "id": 54, "name": "Data Logger Módulo", "location": "OF-REP-A,B", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Módulos Electrónicos" },
  { "id": 55, "name": "Modelo Puente Cau Cau", "location": "OF-REP-A,B", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Kits Didácticos" },
  { "id": 56, "name": "Módulo RGB", "location": "OF-REP-A,B", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Optoelectrónica" },
  { "id": 57, "name": "Lentes de Realidad Virtual (Básicos)", "location": "OF-REP-A,B", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "VR y Multimedia" },
  { "id": 58, "name": "Conversor VGA a HDMI", "location": "BO-IZ-D", "stock": 6, "in_use": 0, "damaged": 0, "avail": 6, "cost_center": "Informática", "category": "Cables y Adaptadores" },
  { "id": 59, "name": "Creality Escáner 360", "location": "OF-EST-B-01", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Impresión 3D y Escáneres" },
  { "id": 60, "name": "3D printing RP 700A Pen", "location": "OF-REP-D,E", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Impresión 3D y Escáneres" },
  { "id": 61, "name": "Kit de Energía Renovable", "location": "BO-IZ-D", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Kits Didácticos" },
  { "id": 62, "name": "Téster Multímetro Digital", "location": "BO-IZ-D", "stock": 9, "in_use": 0, "damaged": 0, "avail": 9, "cost_center": "Industrial", "category": "Instrumentos de Medición" },
  { "id": 63, "name": "Kit Atornillador de precisión", "location": "BO-IZ-D", "stock": 10, "in_use": 0, "damaged": 0, "avail": 10, "cost_center": "Informática", "category": "Herramientas Manuales" },
  { "id": 64, "name": "BOMBA DE AGUA 12V/5V", "location": "BO-IZ-C", "stock": 30, "in_use": 0, "damaged": 2, "avail": 28, "cost_center": "Informática", "category": "Actuadores y Mecánica" },
  { "id": 65, "name": "Pistola de Calor", "location": "OF-EST-A-01", "stock": 3, "in_use": 0, "damaged": 1, "avail": 2, "cost_center": "Industrial", "category": "Herramientas Eléctricas" },
  { "id": 66, "name": "Interruptor Inteligente Sonoff 1 canal", "location": "BO-IZ-C", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Módulos e IoT" },
  { "id": 67, "name": "BOLSA CABLES DUPONT MACHO-HEMBRA", "location": "BO-IZ-C", "stock": 62, "in_use": 0, "damaged": 0, "avail": 62, "cost_center": "Informática", "category": "Cables y Conectores" },
  { "id": 68, "name": "Kit Explore IoT Rev2 Arduino", "location": "BO-IZ-C", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Kits Didácticos" },
  { "id": 69, "name": "Mandriles Porta Broca", "location": "BO-IZ-C", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Industrial", "category": "Herramientas y Brocas" },
  { "id": 70, "name": "Pasta de Soldar", "location": "BO-DE-D", "stock": 5, "in_use": 0, "damaged": 0, "avail": 5, "cost_center": "Industrial", "category": "Consumibles de Soldadura" },
  { "id": 71, "name": "Rollo estaño 50%", "location": "BO-DE-D", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "Consumibles de Soldadura" },
  { "id": 72, "name": "Juego de llaves Allen", "location": "BO-IZ-C", "stock": 2, "in_use": 1, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Herramientas Manuales" },
  { "id": 73, "name": "Guantes Multifunción (Par)", "location": "BO-IZ-C", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Industrial", "category": "Seguridad y EPP" },
  { "id": 74, "name": "Medidor de PH Digital", "location": "BO-IZ-C", "stock": 6, "in_use": 0, "damaged": 0, "avail": 6, "cost_center": "Ambas Carreras", "category": "Instrumentos de Medición" },
  { "id": 75, "name": "Rollo de hilos / Alambre", "location": "BO-IZ-C", "stock": 7, "in_use": 0, "damaged": 0, "avail": 7, "cost_center": "Industrial", "category": "Consumibles" },
  { "id": 76, "name": "Anemómetro Digital", "location": "BO-IZ-C", "stock": 6, "in_use": 0, "damaged": 0, "avail": 6, "cost_center": "Industrial", "category": "Instrumentos de Medición" },
  { "id": 77, "name": "Módulo Fuente de Alimentación Arduino", "location": "BO-IZ-C", "stock": 9, "in_use": 0, "damaged": 0, "avail": 9, "cost_center": "Ambas Carreras", "category": "Alimentación y Fuentes" },
  { "id": 78, "name": "Link cable Oculus 5 m", "location": "BO-IZ-A,B", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "VR y Multimedia" },
  { "id": 79, "name": "Kit R2 Engineering", "location": "BO-IZ-A,B", "stock": 6, "in_use": 0, "damaged": 0, "avail": 6, "cost_center": "Industrial", "category": "Kits Didácticos" },
  { "id": 80, "name": "Lentes Meta Quest 2 128GB", "location": "BO-IZ-A,B", "stock": 10, "in_use": 0, "damaged": 0, "avail": 10, "cost_center": "Ambas Carreras", "category": "VR y Multimedia" },
  { "id": 81, "name": "KeyStudio 37 in one Starter kit", "location": "BO-IZ-A,B", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Kits Didácticos" },
  { "id": 82, "name": "KeyStudio frog robot for arduino", "location": "BO-IZ-A,B", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Robótica" },
  { "id": 83, "name": "Kit Opener Herramientas", "location": "BO-IZ-A,B", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "Herramientas Manuales" },
  { "id": 84, "name": "Gelatina en Polvo (Uso Lab)", "location": "BO-DE-B", "stock": 7, "in_use": 0, "damaged": 0, "avail": 7, "cost_center": "Industrial", "category": "Consumibles Químicos" },
  { "id": 85, "name": "Filamento de Impresión 3D Azul (1kg)", "location": "OF-REP-D,E", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Ambas Carreras", "category": "Impresión 3D y Filamentos" },
  { "id": 86, "name": "Filamento de Impresión 3D Naranjo (1kg)", "location": "OF-REP-D,E", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Ambas Carreras", "category": "Impresión 3D y Filamentos" },
  { "id": 87, "name": "Filamento de Impresión 3D Amarillo (1kg)", "location": "OF-REP-D,E", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Impresión 3D y Filamentos" },
  { "id": 88, "name": "Filamento de Impresión 3D Rojo (1kg)", "location": "OF-REP-D,E", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "Impresión 3D y Filamentos" },
  { "id": 89, "name": "Filamento de Impresión 3D Silver/Plateado (1kg)", "location": "OF-REP-D,E", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Ambas Carreras", "category": "Impresión 3D y Filamentos" },
  { "id": 90, "name": "Filamento de Impresión 3D Beige (1kg)", "location": "OF-REP-D,E", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Ambas Carreras", "category": "Impresión 3D y Filamentos" },
  { "id": 91, "name": "Filamento de Impresión 3D Blanco (1kg)", "location": "OF-REP-D,E", "stock": 6, "in_use": 0, "damaged": 0, "avail": 6, "cost_center": "Ambas Carreras", "category": "Impresión 3D y Filamentos" },
  { "id": 92, "name": "Sensor pulso cardíaco MAX30100", "location": "BO-DE-C-01", "stock": 5, "in_use": 0, "damaged": 0, "avail": 5, "cost_center": "Informática", "category": "Sensores Biomédicos" },
  { "id": 93, "name": "Módulo ATGM336H GPS", "location": "BO-DE-C-01", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Informática", "category": "Sensores y GPS" },
  { "id": 94, "name": "Sensor giroscopio-acelerómetro MPU6050", "location": "BO-DE-C-01", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Informática", "category": "Sensores" },
  { "id": 95, "name": "Sensor intensidad lumínica (BH1750/LDR)", "location": "BO-DE-C-01", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Informática", "category": "Sensores" },
  { "id": 96, "name": "Batería Li-Ion 3,7v", "location": "BO-DE-C-01", "stock": 14, "in_use": 0, "damaged": 0, "avail": 14, "cost_center": "Ambas Carreras", "category": "Alimentación y Baterías" },
  { "id": 97, "name": "Módulo de carga Micro USB TP4056", "location": "BO-DE-C-01", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Industrial", "category": "Alimentación y Módulos" },
  { "id": 98, "name": "Lector USB tarjeta SD", "location": "BO-DE-C-01", "stock": 8, "in_use": 0, "damaged": 0, "avail": 8, "cost_center": "Ambas Carreras", "category": "Memorias y Almacenamiento" },
  { "id": 99, "name": "Celda Peltier TEC1-12706", "location": "BO-DE-C-01", "stock": 7, "in_use": 0, "damaged": 0, "avail": 7, "cost_center": "Ambas Carreras", "category": "Termoelectricidad y Actuadores" },
  { "id": 100, "name": "Sensor Reconocimiento de Color TCS3200", "location": "BO-DE-C-01", "stock": 4, "in_use": 2, "damaged": 0, "avail": 2, "cost_center": "Ambas Carreras", "category": "Sensores" },
  { "id": 101, "name": "Smart home kit for arduino", "location": "BO-IZ-A,B", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "Kits Didácticos" },
  { "id": 102, "name": "Sensor Micro-ondas Doppler", "location": "BO-DE-C-01", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Ambas Carreras", "category": "Sensores" },
  { "id": 103, "name": "Módulo Bluetooth HC-05/06", "location": "BO-DE-C-01", "stock": 5, "in_use": 0, "damaged": 0, "avail": 5, "cost_center": "Ambas Carreras", "category": "Comunicación Inalámbrica" },
  { "id": 104, "name": "Kit 37 Sensores para Arduino", "location": "BO-DE-D", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Ambas Carreras", "category": "Sensores" },
  { "id": 105, "name": "Agorex 60 Adhesivo", "location": "BO-DE-D", "stock": 1, "in_use": 0, "damaged": 1, "avail": 0, "cost_center": "Ambas Carreras", "category": "Consumibles y Pegamentos" },
  { "id": 106, "name": "Cinta Aislante", "location": "BO-DE-D", "stock": 17, "in_use": 5, "damaged": 0, "avail": 12, "cost_center": "Ambas Carreras", "category": "Consumibles" },
  { "id": 107, "name": "Kit Atornilladores Pro", "location": "BO-IZ-A,B", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Industrial", "category": "Herramientas Manuales" },
  { "id": 108, "name": "Blower / Soplador de Aire", "location": "BO-IZ-A,B", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Herramientas Eléctricas" },
  { "id": 109, "name": "13 in 1 educational solar robot", "location": "OF-REP-C", "stock": 6, "in_use": 0, "damaged": 0, "avail": 6, "cost_center": "Industrial", "category": "Robótica y Kits" },
  { "id": 110, "name": "14 in 1 educational solar robot", "location": "OF-REP-C", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Robótica y Kits" },
  { "id": 111, "name": "Compresor Planet Air", "location": "PISO", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Equipos Pesados" },
  { "id": 112, "name": "Medidor RLC de Banco", "location": "OF-EST-A-02", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Instrumentos de Medición" },
  { "id": 113, "name": "Banco de soldadura Atten", "location": "OF-EST-B-02", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "Estaciones de Trabajo" },
  { "id": 114, "name": "SERVO MOTOR SG90 / MG996R", "location": "BO-DE-C-02", "stock": 68, "in_use": 12, "damaged": 2, "avail": 54, "cost_center": "Ambas Carreras", "category": "Actuadores y Motores" },
  { "id": 115, "name": "Kit herramientas 42 piezas", "location": "BO-DE-A", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "Herramientas Manuales" },
  { "id": 116, "name": "Kit desatornilladores 26 piezas", "location": "BO-DE-A", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Herramientas Manuales" },
  { "id": 117, "name": "Tape / Cinta adhesiva especial", "location": "BO-IZ-A,B", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Consumibles" },
  { "id": 118, "name": "Trípode para Cámara / Escáner", "location": "BO-IZ-A,B", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Soportes y Accesorios" },
  { "id": 119, "name": "Arduino Nano", "location": "BO-DE-D", "stock": 9, "in_use": 0, "damaged": 0, "avail": 9, "cost_center": "Ambas Carreras", "category": "Microcontroladores e IoT" },
  { "id": 120, "name": "Arduino R4 WiFi / Minima", "location": "BO-DE-D", "stock": 23, "in_use": 0, "damaged": 0, "avail": 23, "cost_center": "Informática", "category": "Microcontroladores e IoT" },
  { "id": 121, "name": "Tawin motor DC dual", "location": "PISO", "stock": 5, "in_use": 0, "damaged": 0, "avail": 5, "cost_center": "Ambas Carreras", "category": "Actuadores y Motores" },
  { "id": 122, "name": "Science Kit Physics / Electronics", "location": "BO-DE-D", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Kits Didácticos" },
  { "id": 123, "name": "Resina Impresora 3D UV (1 Litro)", "location": "PISO", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "Impresión 3D y Filamentos" },
  { "id": 124, "name": "Panel Fotovoltaico 5v 0.5w", "location": "BO-DE-C-04", "stock": 34, "in_use": 3, "damaged": 0, "avail": 31, "cost_center": "Ambas Carreras", "category": "Energías Renovables" },
  { "id": 125, "name": "Agua destilada (Bidón 5L)", "location": "PISO", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Consumibles Químicos" },
  { "id": 126, "name": "Sensor Temperatura y Humedad DHT11/DHT22", "location": "BO-DE-C-02", "stock": 32, "in_use": 0, "damaged": 0, "avail": 32, "cost_center": "Ambas Carreras", "category": "Sensores" },
  { "id": 127, "name": "Ruedas de Robótica Chasis", "location": "BO-DE-D", "stock": 152, "in_use": 21, "damaged": 0, "avail": 131, "cost_center": "Informática", "category": "Robótica y Mecánica" },
  { "id": 128, "name": "Vernier Charger Sensor Pasco", "location": "BO-IZ-A,B", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Informática", "category": "Sensores y Medición" },
  { "id": 129, "name": "Gabinete organizador tipo cajonera", "location": "MESÓN DE TRABAJO", "stock": 2, "in_use": 2, "damaged": 0, "avail": 0, "cost_center": "Industrial", "category": "Mobiliario y Organización" },
  { "id": 130, "name": "Inversor de Corriente 500 W", "location": "ESTRUCTURA METALICA FOTOVOL.", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Energías Renovables" },
  { "id": 131, "name": "Controlador Solar PWM", "location": "ESTRUCTURA METALICA FOTOVOL.", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Energías Renovables" },
  { "id": 132, "name": "Batería ciclo profundo AGM 100Ah 12V", "location": "ESTRUCTURA METALICA FOTOVOL.", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Energías Renovables" },
  { "id": 133, "name": "Panel Solar 100 W Monocristalino", "location": "ESTRUCTURA METALICA FOTOVOL.", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Energías Renovables" },
  { "id": 134, "name": "Sensor de Gas MQ-2 / MQ-7", "location": "BO-DE-C-02", "stock": 32, "in_use": 0, "damaged": 0, "avail": 32, "cost_center": "Ambas Carreras", "category": "Sensores" },
  { "id": 135, "name": "Módulo de Turbiedad de Agua", "location": "BO-DE-C-02", "stock": 6, "in_use": 0, "damaged": 0, "avail": 6, "cost_center": "Industrial", "category": "Sensores" },
  { "id": 136, "name": "Sensor de Partículas Polvo PM2.5", "location": "BO-DE-C-02", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "Sensores" },
  { "id": 137, "name": "Multiplexor análogo 16 canales CD74HC4067", "location": "BO-DE-C-02", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Ambas Carreras", "category": "Módulos Electrónicos" },
  { "id": 138, "name": "ESP-01 Módulo WiFi", "location": "BO-DE-C-02", "stock": 6, "in_use": 0, "damaged": 0, "avail": 6, "cost_center": "Ambas Carreras", "category": "Comunicación Inalámbrica" },
  { "id": 139, "name": "Tira led RGB Neopixel", "location": "BO-DE-C-02", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Ambas Carreras", "category": "Optoelectrónica" },
  { "id": 140, "name": "Módulo lector RFID RC522", "location": "BO-DE-C-02", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "RFID y Control Acceso" },
  { "id": 141, "name": "Tarjeta RFID 13.56MHz", "location": "BO-DE-C-02", "stock": 14, "in_use": 4, "damaged": 2, "avail": 8, "cost_center": "Industrial", "category": "RFID y Control Acceso" },
  { "id": 142, "name": "Sensor de Temperatura por Infrarrojo MLX90614", "location": "BO-DE-C-03", "stock": 10, "in_use": 0, "damaged": 0, "avail": 10, "cost_center": "Ambas Carreras", "category": "Sensores" },
  { "id": 143, "name": "Sensor de Temperatura DS18B20 Sonda", "location": "BO-DE-C-03", "stock": 9, "in_use": 0, "damaged": 0, "avail": 9, "cost_center": "Ambas Carreras", "category": "Sensores" },
  { "id": 144, "name": "Sensor Ultrasonido HC-SR04", "location": "BO-DE-C-03", "stock": 70, "in_use": 21, "damaged": 0, "avail": 49, "cost_center": "Ambas Carreras", "category": "Sensores" },
  { "id": 145, "name": "Sensor humedad de Suelo Capacitivo", "location": "BO-DE-C-03", "stock": 34, "in_use": 0, "damaged": 0, "avail": 34, "cost_center": "Ambas Carreras", "category": "Sensores" },
  { "id": 146, "name": "Sensor Infrarrojo Evitador de Obstáculos", "location": "BO-DE-C-03", "stock": 53, "in_use": 0, "damaged": 0, "avail": 53, "cost_center": "Ambas Carreras", "category": "Sensores" },
  { "id": 147, "name": "Módulo Controlador L298N Puente H", "location": "BO-DE-C-03", "stock": 48, "in_use": 18, "damaged": 8, "avail": 22, "cost_center": "Informática", "category": "Actuadores y Motores" },
  { "id": 148, "name": "Multímetro-Amperímetro de Gancho", "location": "BO-DE-C-03", "stock": 21, "in_use": 4, "damaged": 0, "avail": 17, "cost_center": "Industrial", "category": "Instrumentos de Medición" },
  { "id": 149, "name": "CONTROLADOR MOTOR PASO A PASO A4988/TB6600", "location": "BO-DE-C-04", "stock": 17, "in_use": 0, "damaged": 0, "avail": 17, "cost_center": "Industrial", "category": "Actuadores y Motores" },
  { "id": 150, "name": "MOTOR PASO A PASO NEMA 17", "location": "BO-DE-C-04", "stock": 17, "in_use": 0, "damaged": 0, "avail": 17, "cost_center": "Industrial", "category": "Actuadores y Motores" },
  { "id": 151, "name": "Sensor Celda de Carga + Módulo HX711", "location": "BO-DE-C-04", "stock": 8, "in_use": 0, "damaged": 0, "avail": 8, "cost_center": "Industrial", "category": "Sensores" },
  { "id": 152, "name": "Filamento PETG negro (1kg)", "location": "OF-REP-D,E", "stock": 5, "in_use": 1, "damaged": 0, "avail": 4, "cost_center": "Informática", "category": "Impresión 3D y Filamentos" },
  { "id": 153, "name": "Fotoresistencia LDR", "location": "OF-EST-A-01", "stock": 60, "in_use": 0, "damaged": 0, "avail": 60, "cost_center": "Informática", "category": "Componentes Pasivos" },
  { "id": 154, "name": "Caja de diodos rectificadores 1N4007", "location": "OF-EST-A-01", "stock": 10, "in_use": 0, "damaged": 0, "avail": 10, "cost_center": "Informática", "category": "Componentes Pasivos" },
  { "id": 155, "name": "Kit armable de peso con sensor de carga", "location": "OF-EST-A-01", "stock": 8, "in_use": 0, "damaged": 0, "avail": 8, "cost_center": "Industrial", "category": "Kits Didácticos" },
  { "id": 156, "name": "Soldadura estaño 1mm 16 gramos", "location": "OF-EST-A-01", "stock": 10, "in_use": 0, "damaged": 0, "avail": 10, "cost_center": "Industrial", "category": "Consumibles de Soldadura" },
  { "id": 157, "name": "Sensor de flujo de agua YF-S201", "location": "OF-EST-A-01", "stock": 8, "in_use": 0, "damaged": 0, "avail": 8, "cost_center": "Industrial", "category": "Sensores" },
  { "id": 158, "name": "Probador tester para servo motores", "location": "OF-EST-A-01", "stock": 6, "in_use": 0, "damaged": 0, "avail": 6, "cost_center": "Industrial", "category": "Instrumentos de Medición" },
  { "id": 159, "name": "Módulo seguidor de línea TCRT5000", "location": "OF-EST-A-01", "stock": 20, "in_use": 0, "damaged": 0, "avail": 20, "cost_center": "Industrial", "category": "Sensores" },
  { "id": 160, "name": "Limpia contactos dieléctrico en spray", "location": "OF-EST-A-01", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Consumibles y Mantenimiento" },
  { "id": 161, "name": "Laca fijadora impresión 3D 3DLac", "location": "OF-EST-B-01", "stock": 13, "in_use": 0, "damaged": 0, "avail": 13, "cost_center": "Industrial", "category": "Impresión 3D y Filamentos" },
  { "id": 162, "name": "KIT Sensor óptico con IA DFROBOT HuskyLens", "location": "OF-EST-B-01", "stock": 6, "in_use": 1, "damaged": 0, "avail": 5, "cost_center": "Industrial", "category": "Inteligencia Artificial y Visión" },
  { "id": 163, "name": "Wireless rotary motion sensor Pasco", "location": "OF-REP-D,E", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Sensores y Medición" },
  { "id": 164, "name": "Photogate tape, HIGH resolution Pasco", "location": "OF-EST-A-01", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Industrial", "category": "Sensores y Medición" },
  { "id": 165, "name": "Imanes de Neodimio de alta potencia", "location": "PISO", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Física y Mecánica" },
  { "id": 166, "name": "Economy coils primary and secondary Pasco", "location": "OF-EST-A-02", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Física y Electromagnetismo" },
  { "id": 167, "name": "Electrostatic materials kit Pasco", "location": "OF-EST-A-02", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Física y Electromagnetismo" },
  { "id": 168, "name": "Mini launcher de proyectiles Pasco", "location": "OF-REP-D,E", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Industrial", "category": "Física y Mecánica" },
  { "id": 169, "name": "Carbon paper para experimentos Pasco", "location": "OF-REP-D,E", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Consumibles" },
  { "id": 170, "name": "Black thread alambre/hilo de precisión", "location": "OF-REP-D,E", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Consumibles" },
  { "id": 171, "name": "Brazo robótico Elephant Robotics myCobot", "location": "OF-REP-F", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "Robótica Avanzada" },
  { "id": 172, "name": "Base de fijación brazo robótico Elephant", "location": "OF-EST-A-02", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "Robótica Avanzada" },
  { "id": 173, "name": "Gripper / Pinza para brazo robótico Elephant", "location": "OF-EST-A-02", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Industrial", "category": "Robótica Avanzada" },
  { "id": 174, "name": "CABINA SCANNER 3D Pro", "location": "BO-DE-A", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Industrial", "category": "Impresión 3D y Escáneres" },
  { "id": 175, "name": "FILTRO DE EXTRACCIÓN DE HUMO de soldadura", "location": "BO-DE-B", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Industrial", "category": "Seguridad y EPP" },
  { "id": 176, "name": "ELECTROSCOPIO Didáctico", "location": "BO-DE-B", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Industrial", "category": "Física y Electromagnetismo" },
  { "id": 177, "name": "Batería 9V Recargable NiMH/Li-Ion", "location": "BO-IZ-E,F", "stock": 48, "in_use": 9, "damaged": 0, "avail": 39, "cost_center": "Informática", "category": "Alimentación y Baterías" },
  { "id": 178, "name": "Motor DC 9v estándar", "location": "BO-DE-C-02", "stock": 26, "in_use": 5, "damaged": 5, "avail": 16, "cost_center": "Industrial", "category": "Actuadores y Motores" },
  { "id": 179, "name": "Motor DC 9v con caja reductora", "location": "BO-DE-C-02", "stock": 81, "in_use": 30, "damaged": 30, "avail": 21, "cost_center": "Informática", "category": "Actuadores y Motores" },
  { "id": 180, "name": "Pilas botón CR2032 3V", "location": "BO-IZ-E,F", "stock": 10, "in_use": 1, "damaged": 0, "avail": 9, "cost_center": "Industrial", "category": "Alimentación y Baterías" },
  { "id": 181, "name": "Cargador inteligente de baterías y pilas", "location": "BO-IZ-E,F", "stock": 5, "in_use": 0, "damaged": 0, "avail": 5, "cost_center": "Informática", "category": "Alimentación y Fuentes" },
  { "id": 182, "name": "Filamento PLA negro (1kg)", "location": "OF-REP-D,E", "stock": 4, "in_use": 2, "damaged": 0, "avail": 2, "cost_center": "Industrial", "category": "Impresión 3D y Filamentos" },
  { "id": 183, "name": "Motor 12VDC con reductor 105rpm", "location": "BO-DE-C-02", "stock": 60, "in_use": 40, "damaged": 0, "avail": 20, "cost_center": "Ambas Carreras", "category": "Actuadores y Motores" },
  { "id": 184, "name": "Tapete antiestática ESD con conexión a tierra", "location": "MESÓN DE TRABAJO", "stock": 3, "in_use": 0, "damaged": 0, "avail": 3, "cost_center": "Ambas Carreras", "category": "Estaciones de Trabajo" },
  { "id": 185, "name": "Filamento PLA Dorado / Gold (1kg)", "location": "OF-REP-D,E", "stock": 12, "in_use": 0, "damaged": 0, "avail": 12, "cost_center": "Industrial", "category": "Impresión 3D y Filamentos" },
  { "id": 186, "name": "Pantalla Touch para Raspberry Pi 7 pulgadas", "location": "BO-DE-C-04", "stock": 9, "in_use": 1, "damaged": 0, "avail": 8, "cost_center": "Industrial", "category": "Displays y Pantallas" },
  { "id": 187, "name": "KIT RaspBerry PI 5 8GB Completo", "location": "BO-DE-C-04", "stock": 10, "in_use": 1, "damaged": 0, "avail": 9, "cost_center": "Informática", "category": "SBC y Procesadores" },
  { "id": 188, "name": "RaspBerry PI 4 8GB Placa sola", "location": "BO-DE-C-04", "stock": 1, "in_use": 0, "damaged": 0, "avail": 1, "cost_center": "Ambas Carreras", "category": "SBC y Procesadores" },
  { "id": 189, "name": "RaspBerry PI 5 4GB Placa sola", "location": "BO-DE-C-04", "stock": 2, "in_use": 0, "damaged": 0, "avail": 2, "cost_center": "Industrial", "category": "SBC y Procesadores" },
  { "id": 190, "name": "Batería 12V 7,2Ah Sellada de Ácido-Plomo", "location": "BO-IZ-E,F", "stock": 18, "in_use": 0, "damaged": 0, "avail": 18, "cost_center": "Ambas Carreras", "category": "Alimentación y Baterías" },
  { "id": 191, "name": "Módulo GPS NEO-8M con Antena", "location": "BO-DE-C-01", "stock": 7, "in_use": 0, "damaged": 0, "avail": 7, "cost_center": "Informática", "category": "Sensores y GPS" },
  { "id": 192, "name": "Pack Barra de silicona (20 unidades)", "location": "BO-IZ-E,F", "stock": 5, "in_use": 1, "damaged": 0, "avail": 4, "cost_center": "Ambas Carreras", "category": "Consumibles" },
  { "id": 193, "name": "Pegamento Loctite cianocrilato instantáneo", "location": "BO-IZ-E,F", "stock": 8, "in_use": 3, "damaged": 0, "avail": 5, "cost_center": "Ambas Carreras", "category": "Consumibles" },
  { "id": 194, "name": "Corta cartón metálico (Cúter)", "location": "BO-IZ-E,F", "stock": 4, "in_use": 0, "damaged": 0, "avail": 4, "cost_center": "Ambas Carreras", "category": "Herramientas Manuales" },
  { "id": 195, "name": "Hoja Repuesto Corta Cartón (Caja)", "location": "BO-IZ-E,F", "stock": 10, "in_use": 1, "damaged": 0, "avail": 9, "cost_center": "Ambas Carreras", "category": "Consumibles" },
  { "id": 196, "name": "Cinta de Montaje doble faz", "location": "BO-IZ-E,F", "stock": 4, "in_use": 2, "damaged": 0, "avail": 2, "cost_center": "Ambas Carreras", "category": "Consumibles" },
  { "id": 197, "name": "Kit Robot Detector de Obstáculos 2WD", "location": "BO-DE-C-04", "stock": 20, "in_use": 1, "damaged": 0, "avail": 19, "cost_center": "Informática", "category": "Robótica" }
]

def seed_database(db: Session):
    existing_count = db.query(models.Item).count()
    if existing_count == 0:
        for item_data in INITIAL_ITEMS:
            item_obj = models.Item(
                id=item_data["id"],
                name=item_data["name"],
                location=item_data["location"],
                stock=item_data["stock"],
                in_use=item_data["in_use"],
                damaged=item_data["damaged"],
                avail=item_data["avail"],
                cost_center=item_data["cost_center"],
                category=item_data["category"]
            )
            db.add(item_obj)
        db.commit()
        print(f"[SEED] OK: {len(INITIAL_ITEMS)} articulos precargados en la base de datos.")
    else:
        print(f"[SEED] Inventario ya contiene {existing_count} artículos. Se omitió la precarga.")
